export const libertyflames = [
    'sports/baseball/schedule',
    'sports/mens-basketball/schedule',
    'sports/cross-country/schedule',
    'sports/football/schedule',
    // 'sports/mens-golf/schedule',
    'sports/mens-soccer/schedule',
    'sports/mens-tennis/schedule',
    // 'sports/track-and-field/schedule',
    'sports/womens-basketball/schedule',
    'sports/field-hockey/schedule',
    'sports/womens-lacrosse/schedule',
    'sports/womens-soccer/schedule',
    'sports/softball/schedule',
    'sports/womens-swimming-and-diving/schedule',
    'sports/womens-tennis/schedule',
    'sports/womens-volleyball/schedule',
];

export const syracuse = [
    'sports/mens-basketball/schedule',
    'sports/cross-country/schedule',
    'sports/football/schedule',
    'sports/mens-lacrosse/schedule',
    'sports/mens-crew/schedule',
    'sports/mens-soccer/schedule',
    'sports/track-and-field/schedule',
    'sports/womens-basketball/schedule',
    'sports/womens-cross-country/schedule',
    'sports/field-hockey/schedule',
    'sports/womens-ice-hockey/schedule',
    // 'sports/womens-lacrosse/schedule',
    // 'sports/rowing/schedule',
    'sports/womens-soccer/schedule',
    'sports/softball/schedule',
    'sports/womens-tennis/schedule',
    'sports/track-and-field/schedule',
    'sports/womens-volleyball/schedule',
];